### ISSUE TITLE
add-admin-page

### ISSUE THREAD

**Issue by oXyut** [oXyut/check-attendance-docker#3]
## 一言で
- 現在のユーザ一覧の取得とユーザを追加できるページの作成
## 詳細
- 現在ルート"/"にとりあえず置かれている内容をadminに移して運用できるようにする
- ヘッダーのアイコン：`import { FaUserCog } from "react-icons/fa";`
- とりあえずユーザ一覧を取得して表として見せる
  - 「ユーザー一覧」の文字はh2とかh3で
  - これ使ってみて：https://www.material-react-table.com
  - idは途中で省略して横スクロールできるように
  - 10件を上限に、ボタンで次の表に遷移できるような実装ができるはず
- ユーザを追加できるフォームを作成
  - 「ユーザー追加フォーム」の文字はh2とかh3で
  -  時刻選択はドラムロール（年月日は2000年1月1日で固定してください）
  - 名前と日付入れない限りボタンはdisabledに
- 余裕があればめっちゃ簡単なパスワード保護ができると良いかも（`useState`とかで）
- ゆくゆくは表から各人のページに飛べるようなルーティングも設定したい

## UIイメージ
![スクリーンショット 2023-12-14 16 29 26](https://github.com/oXyut/check-attendance-docker/assets/79395449/6c17c67f-19cd-4029-bcd8-1e7416364ee1)

## タスク
- admin/page.tsxの追加
- ユーザ一覧の表の作成
- ユーザー追加フォームの作成
- (more)パスワード保護
- (more)ルーティングの設定

**Comment by oXyut** [comment]
アイコンはこれを使って
`import { FaUserCog } from "react-icons/fa";`

**Comment by oXyut** [comment]
テーブルの実装はかっこよさそうだからこれ使ってみて
https://www.material-react-table.com

**Comment by oXyut** [comment]
@Leo-Ando 表の作成ありがとうございます。大変良くできていると思いますが、以下の点を修正してほしいです

- [ ] ダークモードにするとヘッダーが真っ白になってしまうので修正してほしいです

![image](https://github.com/oXyut/check-attendance-docker/assets/79395449/f647684f-719d-4d95-a7fc-e2560c3a890b)

あと、以下の点を変更していただきたいです

- [ ] 全体で何件中の何件を見せているよ、というような表示が右下あたりに欲しいです（たとえば、1-10 / 21 みたいな感じです）。
- [ ] 「前へ」「次へ」ではなく、矢印にした方が直観的なUIになるかと思います。`import { FaAngleRight } from "react-icons/fa";`と`import { FaAngleLeft } from "react-icons/fa";`を使ってください
- [ ] これ以上前/後に行けない場合は、色をdisabledにしてクリックできないようにした方がいいと思います

以上を踏まえたUIのイメージはこんな感じです。よろしくお願いいたします。

![image](https://github.com/oXyut/check-attendance-docker/assets/79395449/e0746cd8-700c-448f-8b43-0886aea8c36f)

**Comment by Leo-Ando** [comment]
修正と変更完了しました。ユーザーの追加とzodでの形式の検証に進みます。
